### PR TITLE
docs: add description and usage to readme

### PR DESCRIPTION
**Pull request by barriebyron**
Hi, Game of Zones devs,

I was introducing the Game of Zones web to a new Cosmosnaut today and realized that the project readme lacked a basic description and use instructions.

Here is my contribution to the project readme so that others can discover and enjoy this awesome block explorer. Thank you for this beautiful visualization of the Cosmos chains that are part of the #IBCGang.

### CODE REVIEW

**Comment by barriebyron** [comment]
@Raumo0 take a look

**Comment by barriebyron** [comment]
@sarious do you know who might be interested in reviewing and approving this PR?

**Comment by Raumo0** [comment]
@barriebyron Thanks for your pull request, this is the first third party pull request to our repositories!😃 Also sorry for the late reply. I will review your request very soon. Thank you very much!

**Comment by Raumo0** [comment]
@barriebyron Thank you, your changes have been added. Given our recent cashflow update, we need to add more descriptions later.

**Pull request merged**
